### ISSUE TITLE
Calibration mismatch

### ISSUE THREAD

**Issue by tischi** [mobie/spatial-transcriptomics-example-project#10]
I can open the spots 🥳 

But there seems to be  a calibration mismatch between the spots and the image data:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/2157566/192466000-5af85ffb-d3bd-4033-b426-a56bee9c5464.png">

**Comment by constantinpape** [comment]
> I can open the spots partying_face

Nice!

> But there seems to be a calibration mismatch between the spots and the image data:

I think the image data is missing the calibration info. I should have it somewhere and will add it to the image data.

**Comment by constantinpape** [comment]
The image actually has calibration info. I think that the problem is that the spots are in uncalibrated pixel coordinates, I will update it.

**Comment by constantinpape** [comment]
I have updated the coordinates in the table, they should have the same scale as the image now.
