### ISSUE TITLE
spot tables start with emtpy string column name

### ISSUE THREAD

**Issue by tischi** [mobie/spatial-transcriptomics-example-project#14]
@constantinpape I think your code added the row number to the tables, with an empty string as column name. I think we don't allow this in the spec, do we?

<img width="731" alt="image" src="https://user-images.githubusercontent.com/2157566/192547814-8d16bc9f-302b-4db5-89ed-46b689534519.png">

**Comment by constantinpape** [comment]
Yeah, that's an annoying pandas thing that creeps in if one isn't careful...
I fixed it.
