### ISSUE TITLE
Names for spot displays are missing

### ISSUE THREAD

**Issue by tischi** [mobie/spatial-transcriptomics-example-project#15]
@constantinpape 

[here](https://github.com/mobie/spatial-transcriptomics-example-project/blob/8b651452ea2e9fd30d5a15fa86ad9fe3129e680f/data/pos42-spatial-transcriptomics/dataset.json#L105) and in other places, the `name` field is missing. Could you please add some names? Otherwise it looks weird in the UI.

**Comment by constantinpape** [comment]
Done
