### ISSUE TITLE
image_and_spots

### ISSUE THREAD

**Issue by tischi** [mobie/spatial-transcriptomics-example-project#16]
Should the spots coincide with spot signal in the image? Because, for me, they don't.

<img width="962" alt="image" src="https://user-images.githubusercontent.com/2157566/192565817-8531f29f-0443-4bcf-aa08-2b22c2309044.png">

**Comment by constantinpape** [comment]
No, the image is a membrane marker, the spots are sequencing readouts that were spatially mapped to the same space, they are not expected to be very well correlated.
