### ISSUE TITLE
boundingBox dimensions order 

### ISSUE THREAD

**Issue by tischi** [mobie/spatial-transcriptomics-example-project#19]
https://github.com/mobie/spatial-transcriptomics-example-project/blob/65f5aa7c504c3b9ee145aa53d1ac8f6be1d20020/data/pos42-spatial-transcriptomics/dataset.json#L62

you have z,y,x
I think we should have x,y,z ?

**Comment by constantinpape** [comment]
Indeed, the usual confusion between python and java...
It's fixed now.
