### ISSUE TITLE
superfluous `boundingBoxMax`

### ISSUE THREAD

**Issue by tischi** [mobie/spatial-transcriptomics-example-project#20]
https://github.com/mobie/spatial-transcriptomics-example-project/blob/a830ffd5f268fa44248bee68799ccb792ce16262/data/pos42-spatial-transcriptomics/dataset.json#L60

The  first `boundingBoxMax` in the above link is wrong and should be removed.

**Comment by constantinpape** [comment]
Indeed, this happened when trying to reverse the axis order for the bounding boxes and I didn't catch it. It's fixed now.

**Comment by tischi** [comment]
Thanks! This works now.
I am not sure the bounding box is the best though. You are choosing a z range from 0 to 24, but the data only lives at z=8. If you'd restrict this more the focus button of the spot source would bring the user to a plane where there actually are some spots. Right now, it is a bit confusing that one clicks `F` and does not see anything.

**Comment by constantinpape** [comment]
Go ahead and change this as you need it.

**Comment by tischi** [comment]
For me it is fine, it is more a suggestion for when we add this to the publication.

**Comment by constantinpape** [comment]
> For me it is fine, it is more a suggestion for when we add this to the publication.

We will have a bigger dataset including a grid view for the publication, this is mostly a test for development.
