### ISSUE TITLE
Table loading/initialization is slow

### ISSUE THREAD

**Issue by constantinpape** [mobie/spatial-transcriptomics-example-project#23]
I benchmarked loading the tables in python (using pandas) and compared a bit to the loading times for comparable views in MoBIE and this is 1 (loading from github) to 2 (loading from filesystem) orders of magnitude faster in python. And the loading times in MoBIE seem to not be influenced much by loading from filesystem vs. from github. See the benchmarks here:

https://github.com/mobie/spatial-transcriptomics-example-project/tree/main/table-benchmark

Note that this is ofc not quite fair, since there is more happening in MoBIE than just loading the table and putting it into a datastructure like a pandas DataFrame, but still this difference in speed is quite extreme and may point at inefficiencies we could remove to speed this up on the java side.

**Comment by tischi** [comment]
Interesting. 

The code to read the tables in MoBIE is now quite simple: https://github.com/mobie/mobie-viewer-fiji/blob/898d924bdafdabf9955f3e543f6ba4572da8d6e2/src/main/java/org/embl/mobie/viewer/table/saw/TableSawHelper.java#L11

Which table should I use for the benchmarking?
This one?
https://github.com/mobie/spatial-transcriptomics-example-project/blob/ba3d3a6e9d3b4fa04bc114fd80e06cee6d80aa62/table-benchmark/load_single_table.py#L24

**Comment by tischi** [comment]
Notes:

1. download the table
2. benchmark reading directly with TableSaw (not as a two step process like now)
3. benchmark reading and parsing sequentially (as it is implemented now)
4. consider sharing a link to the table with the TableSaw developer, asking for advice

**Comment by tischi** [comment]
Interesting? 
https://github.com/jtablesaw/tablesaw/issues/5

**Comment by tischi** [comment]
https://jtablesaw.github.io/tablesaw/userguide/importing_data

We could try if it is faster if we tell it that all columns are of data type String.

**Comment by constantinpape** [comment]
> Which table should I use for the benchmarking? This one?
> 
> https://github.com/mobie/spatial-transcriptomics-example-project/blob/ba3d3a6e9d3b4fa04bc114fd80e06cee6d80aa62/table-benchmark/load_single_table.py#L24

Yep, that's the table I have used in the `single_table` benchmarks, so makes sense if you use it as well.

> Interesting?
> [jtablesaw/tablesaw#5](https://github.com/jtablesaw/tablesaw/issues/5)

I also don't know what saw files are, probably something internal to jtablesaw?!

> https://jtablesaw.github.io/tablesaw/userguide/importing_data
> 
> We could try if it is faster if we tell it that all columns are of data type String.

I guess for many columns (`region_id`, `label_id`, `spot_id`, `anchor*`, `bb*`, `x`, `y`, `z`) we can also deduce the type from the name.

Overall: I think the first important thing to check is how fast loading the table is with tablesaw compared to pandas. Then we'll see if the big difference in speed is because of this, or if it comes from some other things that happen in views with tables.

**Comment by tischi** [comment]
It is a bit complex, because I think there is caching on the system level going on, i.e. things take very different amounts of time depending on the sequence in which I do them.
Here is one example:

```
Table source: https://raw.githubusercontent.com/mobie/spatial-transcriptomics-example-project/main/data/pos42/tables/transcriptome/default.tsv
Read Table to String, using IOHelper.read [ms]: 897
Open Table InputStream [ms]: 3
Build Table from InputStream [ms]: 1701
Open InputStream [ms]: 4
Read InputStream to String, using IOUtils.toString [ms]: 125
Read Table to String, using IOHelper.read [ms]: 143
Parse Table from String [ms]: 290
```

Code: https://github.com/mobie/mobie-viewer-fiji/blob/mobie3/src/test/java/develop/BenchmarkTableSawTableLoading.java

I think, roughly speaking, loading the data from github the first time takes around 1 second, parsing the data into a table takes around 300 ms. My experiments suggest that it is faster to first load the data entirely and only then parse it into a table. The slowest option seems to be to combine the loading and the parsing (`Build Table from InputStream [ms]: 1701`).

**Comment by constantinpape** [comment]
> parsing the data into a table takes around 300 ms.

Ok, that's still fairly slow compared to pandas (50 ms to read from disc and parse it into the dataframe). But I guess we can't do much about the underlying performance of tablesaw. Is there a way to do this with specifiying the column types? Maybe this could speed things up.

**Comment by tischi** [comment]
Yes, we can try, but the main chunk seems to come from loading from github.
Is that faster for you?

**Comment by tischi** [comment]
`Build Table from File [ms]: 1643`

slow

**Comment by tischi** [comment]
https://github.com/jtablesaw/tablesaw/issues/1162

**Comment by tischi** [comment]
Just reading the table into a big string takes 106 ms.

**Comment by constantinpape** [comment]
> Just reading the table into a big string takes 106 ms.

Ok. Could you run https://github.com/mobie/spatial-transcriptomics-example-project/blob/main/table-benchmark/load_single_table.py on the same machine so that we can check if pandas is actually that much faster or if my hard-drive is just faster than yours?

And then let's see a bit if there's suggestions from the tablesaw team on how to speed this up.

**Comment by tischi** [comment]
OK, so if one gives the JIT some time to warm up the table parsing is not too bad:

The average times for parsing the 100k rows from a String are
```
with given column types: 154.1 ms
without given column types: 210.8 ms
```
We could in principle optionally provide the column types by extending the spec, but I am not sure this is worth it?

The loading from github and building the kdTree could be more severe issues....

**Comment by tischi** [comment]
## Fetching large table from github

`https://raw.githubusercontent.com/mobie/spatial-transcriptomics-example-project/main/data/pos42/tables/transcriptome/default.tsv` 

At home (10 Mbps, https://fast.com/): `github [ms]: 4108.4`

At EMBL (250 Mbps): `github [ms]: 205.3`

**Comment by tischi** [comment]
## Fetching small table for github

`https://raw.githubusercontent.com/mobie/spatial-transcriptomics-example-project/main/data/pos42/tables/positions/default.tsv`:

At home (10 Mbps): `github [ms]: 83.95`
At EMBL (250 Mbps): `github [ms]: 38.3`

Not surprisingly this does not scale linear for small files (overhead of opening the connection).

------

## Idea: Have two tables (small and large)?

Based on this, one idea could be to think about having two tables, one with just a subset of the spots and then some logic that the code would later lazy-load the bigger table...kind of a row-chunking prototype. I would then have to replace the kdTree when loading the bigger table. This could be doable but is a bit of a project and I'd have to evaluate how much work on the Java side.

If you have time you could, for testing, replace the current big tables by smaller ones with, e.g., only 1000 spots; so we could already see how fast that would be.

**Comment by tischi** [comment]
Some more thoughts: try to make this smaller: https://raw.githubusercontent.com/mobie/spatial-transcriptomics-example-project/parquet/data/pos42/tables/transcriptome/default.tsv

1. Are all columns needed?
2. Could we express the spot coordinates as integers, e.g. providing a scaling factor?

**Comment by constantinpape** [comment]
> 1. Are all columns needed?

Good point, we can get rid of some columns.

> 2\. Could we express the spot coordinates as integers, e.g. providing a scaling factor?

Yeah, that would also be feasible, but we would need to be a bit more careful.

**Comment by tischi** [comment]
If I limit the building of the table (and kdTree) to 1000 spots it opens in 34 seconds (this is still loading the whole table but on the Java side only consuming 1000 spots).

What do you think? 

Is 34 seconds for this acceptable or should I try to find out how to make that faster? 

If we think this is acceptable I could look into lazily building a larger kdTree "later", after the data has been loaded and a preview is presented.


```
# MoBIE
Opening project: /g/kreshuk/data/marioni/shila/mouse-atlas-2020/ngff
Opening dataset: embryo3
Opening view: stitched-full
Initialising (1/241): MMStack_Pos21_nucleus-marker
Initialising (9/241): MMStack_Pos1_membrane-marker1
Initialising (17/241): MMStack_Pos34_membrane-marker3
Initialising (3/241): MMStack_Pos6_genes
Initialising (5/241): MMStack_Pos36_genes
Initialising (33/241): MMStack_Pos11_genes
Initialising (65/241): MMStack_Pos10_membrane-marker1
Initialising (129/241): MMStack_Pos30_nucleus-marker
Initialising (161/241): MMStack_Pos22_cells
Initialising (193/241): MMStack_Pos16_cells
Initialised 241 data source(s) in 30888 ms, using up to 16 thread(s).
Opened view: stitched-full in 34854 ms.
```

**Comment by constantinpape** [comment]
> Is 34 seconds for this acceptable or should I try to find out how to make that faster?

~~You're referring to the `stitched-full` view now, right? If yes, then I would say 34 seconds is good.~~
Nevermind, yes it is I just read it from the log :).
Yes, I think 34 seconds is good!

Side note: this will ofc be longer when loading from github due to the download speed, there would be a couple things we can still do about that:
- fewer columns (I will look into it)
- subset of genes (I will also look into it)
- using parquet (the data is smaller because it's binary and compressed) -> you could see how much work it would be to support on the `parquet` branch of the example project.

> If we think this is acceptable I could look into lazily building a larger kdTree "later", after the data has been loaded and a preview is presented.

Yeah, if this is not too difficult that would be very cool.

**Comment by tischi** [comment]
```
			// Note that while it appears to be faster to
			// first load the whole table into one big string,
			// it has the drawback that we temporarily need to
			// allocate twice the memory and the GC has some
			// work to do to clean the memory, which may be a bottleneck.
			// Thus, currently I am using an inputStream
			System.out.println("Reading table " + path + "...");
			final long start = System.currentTimeMillis();
			final InputStream inputStream = IOHelper.getInputStream( path );
			// final String string = IOHelper.read( path );
			// https://jtablesaw.github.io/tablesaw/userguide/importing_data.html
			CsvReadOptions.Builder builder = CsvReadOptions.builder( inputStream ).separator( '\t' ).missingValueIndicator( "na", "none", "nan" ).sample( numSamples > 0 ).sampleSize( numSamples ).columnTypesPartial( nameToType );
			final Table rows = Table.read().usingOptions( builder );
			System.out.println("Read table " + path + " with " + rows.rowCount() + " rows in " + ( System.currentTimeMillis() - start ) + " ms." );
```

Currently the table loading and parsing are not separable since I decide to use a stream (see above).

1. For bench-marking I guess I should again make two steps (load, parse) and time them individually? Should I do this right now or wait (until you made all the screen-casts, I would wait because I am not sure this could screw up loading the big view)?
2. If you want to try things out I think you would need to just use a single thread otherwise it can be complicated to interpret the numbers.

**Comment by constantinpape** [comment]
> 1. For bench-marking I guess I should again make two steps (load, parse) and time them individually? Should I do this right now or wait (until you made all the screen-casts, I would wait because I am not sure this could screw up loading the big view)?

I suggest we wait a bit with this, since the performance is good enough now for the first version.

> 2\. If you want to try things out I think you would need to just use a single thread otherwise it can be complicated to interpret the numbers.

Ok, thanks.

I will close this issue now, and we can discuss further steps in https://github.com/mobie/mobie-viewer-fiji/issues/873.
