### ISSUE TITLE
2D KDTree for data with few z values

### ISSUE THREAD

**Issue by tischi** [mobie/spatial-transcriptomics-example-project#27]
Do you think it could make sense to only build a 2D Tree and then implement some other mechanism to find the correct spot along the z-axis? Do you think that could be faster and less memory consuming?

**Comment by constantinpape** [comment]
For the data here: yes, it would make sense.
But we could also have other kinds of spot data that is "truly 3d", and then the this solution would be suboptimal.

You could add some heuristics to determine which situation, for example by checking how many unique z coordinates there are, and choosing the "true 3d" case if there are more z  spot coordinates than the extent along z.
(Computing the uniques is fast, at least in python it only takes 0.000930s for one of the big tables.)

> then implement some other mechanism to find the correct spot along the z-axis

I guess you could have a map from z-index to kd-tree and then round the z-coordinate to get the relevant tree(s).

**Comment by tischi** [comment]
I will close this for now as I don't think it is a super big issue right now.
Please write a similar one in mobie-viewer-fiji, if needed.
