### ISSUE TITLE
Updates on the spatial transcriptomics project

### ISSUE THREAD

**Issue by constantinpape** [mobie/spatial-transcriptomics-example-project#29]
Thanks for uploading the new version of MoBIE-beta @tischi! I tried it for the spatial transcriptomics project now and it works much better:
- Loading the `stitched-full` view now takes 127028 ms (~ 2 min), so much better than before.
- Once loaded browsing of all the spots is very smooth now.

There's a couple minor things that would need to be addressed before I can finalize the screenshots and video for this project:
- The tile grid overlay is now active when opening a MoBIE project and I don't think it can be turned off. Can you please deactivate it in `MoBIE->Open MoBIE Project...`?
- Right now there isn't any message in the log when a new view is being opened. So when opening a view that takes a bit longer it's unclear if something is happening. Could you add some message to the log along the lines `Opening the view {VIEW-NAME}. This may take a couple of minutes for complex views`.
- I would need `additionalTables` working. There's an example view now in the project on the kreshuk group share: `gene-clustering-example`

At some point it would also be interesting to know what the bottlenecks are now in loading this view. Is it loading the tables now? If yes, maybe supporting parquet could still help in speeding this up. But I think it's not a priority now.

**Comment by tischi** [comment]
> I would need additionalTables working. 

Working on it....

**Comment by tischi** [comment]
> Right now there isn't any message in the log when a new view is being opened. So when opening a view that takes a bit longer it's unclear if something is happening. Could you add some message to the log along the lines Opening the view {VIEW-NAME}. This may take a couple of minutes for complex views.

```
if ( dataSources.size() > 20 )
	IJ.log("Initialising " + dataSources.size() + " data sources (this could take a couple of minutes..." );
```

OK?

**Comment by tischi** [comment]
I uploaded a new version where all of the above points should be fixed.

**Comment by constantinpape** [comment]
> ```
> if ( dataSources.size() > 20 )
> 	IJ.log("Initialising " + dataSources.size() + " data sources (this could take a couple of minutes..." );
> ```
> 
> 
>     
>   
> 
> OK?

Looks good!

**Comment by constantinpape** [comment]
I checked and all this works. I will create some follow up issues.
