### ISSUE TITLE
Bug in JSON tableData?

### ISSUE THREAD

**Issue by tischi** [mobie/spatial-transcriptomics-example-project#3]
Here you have:

https://github.com/mobie/spatial-transcriptomics-example-project/blob/ea1100fb140964e75c07fed611d33bc3a6b18021/data/pos42-spatial-transcriptomics/dataset.json#L62

Normally we have:

https://github.com/mobie/platybrowser-project/blob/d82ef21888f77e5774694b8b5cdbabdce46e4cba/data/1.0.1/dataset.json#L357

**Comment by constantinpape** [comment]
You're right, this is a bug, I will fix it.

**Comment by constantinpape** [comment]
It's fixed.
