### ISSUE TITLE
Bug in image Pyramid?

### ISSUE THREAD

**Issue by tischi** [mobie/spatial-transcriptomics-example-project#6]
I am again getting this exception:

`net.imglib2.img.basictypeaccess.volatiles.array.VolatileDoubleArray cannot be cast to net.imglib2.img.basictypeaccess.ShortAccess`

Probably a down-sampled resolution is double?

**Comment by constantinpape** [comment]
Yep, this was probably not fixed for the data here yet. I will take a look later.

**Comment by tischi** [comment]
The higher resolutions just render as black pixels. Maybe some issue in the down-sampling still?

**Comment by constantinpape** [comment]
Ok, I will double check later.

**Comment by constantinpape** [comment]
yes, I understand why...
There are still a lot of bugs in https://github.com/ome/ome-zarr-py ...

**Comment by constantinpape** [comment]
Ah no, in this case this was actually an issue that happened when I tried to fix the issue with the floating points (which is the fault of https://github.com/ome/ome-zarr-py...). I will fix it later and ping you.

**Comment by constantinpape** [comment]
Should be fixed now.
