### ISSUE TITLE
Smaller spots table for testing

### ISSUE THREAD

**Issue by tischi** [mobie/spatial-transcriptomics-example-project#9]
Could we have a smaller spots table for testing?

Takes a while for me to load this at home...

**Comment by constantinpape** [comment]
Sure, how many exactly do you want?

**Comment by tischi** [comment]
Maybe 0.1 of what you had.

**Comment by constantinpape** [comment]
Done, we have the spot source `transcriptome-small` now with only 10% of the data, I also use it in the combined view.
